/* Auto-generated by genmsg_cpp for file /home/haikalpribadi/Workspace/ROS/radiophonic/audiogesture/msg/FeatureVector.msg */
#ifndef AUDIOGESTURE_MESSAGE_FEATUREVECTOR_H
#define AUDIOGESTURE_MESSAGE_FEATUREVECTOR_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace audiogesture
{
template <class ContainerAllocator>
struct FeatureVector_ {
  typedef FeatureVector_<ContainerAllocator> Type;

  FeatureVector_()
  : data()
  {
  }

  FeatureVector_(const ContainerAllocator& _alloc)
  : data(_alloc)
  {
  }

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _data_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  data;


  typedef boost::shared_ptr< ::audiogesture::FeatureVector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::audiogesture::FeatureVector_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct FeatureVector
typedef  ::audiogesture::FeatureVector_<std::allocator<void> > FeatureVector;

typedef boost::shared_ptr< ::audiogesture::FeatureVector> FeatureVectorPtr;
typedef boost::shared_ptr< ::audiogesture::FeatureVector const> FeatureVectorConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::audiogesture::FeatureVector_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::audiogesture::FeatureVector_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace audiogesture

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::audiogesture::FeatureVector_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::audiogesture::FeatureVector_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::audiogesture::FeatureVector_<ContainerAllocator> > {
  static const char* value() 
  {
    return "420cd38b6b071cd49f2970c3e2cee511";
  }

  static const char* value(const  ::audiogesture::FeatureVector_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x420cd38b6b071cd4ULL;
  static const uint64_t static_value2 = 0x9f2970c3e2cee511ULL;
};

template<class ContainerAllocator>
struct DataType< ::audiogesture::FeatureVector_<ContainerAllocator> > {
  static const char* value() 
  {
    return "audiogesture/FeatureVector";
  }

  static const char* value(const  ::audiogesture::FeatureVector_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::audiogesture::FeatureVector_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32[] data\n\
\n\
";
  }

  static const char* value(const  ::audiogesture::FeatureVector_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::audiogesture::FeatureVector_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.data);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct FeatureVector_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::audiogesture::FeatureVector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::audiogesture::FeatureVector_<ContainerAllocator> & v) 
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // AUDIOGESTURE_MESSAGE_FEATUREVECTOR_H

