/* Auto-generated by genmsg_cpp for file /home/haikalpribadi/Workspace/ROS/radiophonic/audiogesture/srv/Bextractor.srv */
#ifndef AUDIOGESTURE_SERVICE_BEXTRACTOR_H
#define AUDIOGESTURE_SERVICE_BEXTRACTOR_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace audiogesture
{
template <class ContainerAllocator>
struct BextractorRequest_ {
  typedef BextractorRequest_<ContainerAllocator> Type;

  BextractorRequest_()
  : args()
  {
  }

  BextractorRequest_(const ContainerAllocator& _alloc)
  : args(_alloc)
  {
  }

  typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _args_type;
  std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  args;


  typedef boost::shared_ptr< ::audiogesture::BextractorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::audiogesture::BextractorRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BextractorRequest
typedef  ::audiogesture::BextractorRequest_<std::allocator<void> > BextractorRequest;

typedef boost::shared_ptr< ::audiogesture::BextractorRequest> BextractorRequestPtr;
typedef boost::shared_ptr< ::audiogesture::BextractorRequest const> BextractorRequestConstPtr;



template <class ContainerAllocator>
struct BextractorResponse_ {
  typedef BextractorResponse_<ContainerAllocator> Type;

  BextractorResponse_()
  {
  }

  BextractorResponse_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::audiogesture::BextractorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::audiogesture::BextractorResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BextractorResponse
typedef  ::audiogesture::BextractorResponse_<std::allocator<void> > BextractorResponse;

typedef boost::shared_ptr< ::audiogesture::BextractorResponse> BextractorResponsePtr;
typedef boost::shared_ptr< ::audiogesture::BextractorResponse const> BextractorResponseConstPtr;


struct Bextractor
{

typedef BextractorRequest Request;
typedef BextractorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct Bextractor
} // namespace audiogesture

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::audiogesture::BextractorRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::audiogesture::BextractorRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::audiogesture::BextractorRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "80df8955b7d65a9ccaa8145f1d8b2f01";
  }

  static const char* value(const  ::audiogesture::BextractorRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x80df8955b7d65a9cULL;
  static const uint64_t static_value2 = 0xcaa8145f1d8b2f01ULL;
};

template<class ContainerAllocator>
struct DataType< ::audiogesture::BextractorRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "audiogesture/BextractorRequest";
  }

  static const char* value(const  ::audiogesture::BextractorRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::audiogesture::BextractorRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string[] args\n\
\n\
";
  }

  static const char* value(const  ::audiogesture::BextractorRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::audiogesture::BextractorResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::audiogesture::BextractorResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::audiogesture::BextractorResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::audiogesture::BextractorResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::audiogesture::BextractorResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "audiogesture/BextractorResponse";
  }

  static const char* value(const  ::audiogesture::BextractorResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::audiogesture::BextractorResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::audiogesture::BextractorResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::audiogesture::BextractorResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::audiogesture::BextractorRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.args);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BextractorRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::audiogesture::BextractorResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BextractorResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<audiogesture::Bextractor> {
  static const char* value() 
  {
    return "80df8955b7d65a9ccaa8145f1d8b2f01";
  }

  static const char* value(const audiogesture::Bextractor&) { return value(); } 
};

template<>
struct DataType<audiogesture::Bextractor> {
  static const char* value() 
  {
    return "audiogesture/Bextractor";
  }

  static const char* value(const audiogesture::Bextractor&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<audiogesture::BextractorRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "80df8955b7d65a9ccaa8145f1d8b2f01";
  }

  static const char* value(const audiogesture::BextractorRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<audiogesture::BextractorRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "audiogesture/Bextractor";
  }

  static const char* value(const audiogesture::BextractorRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<audiogesture::BextractorResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "80df8955b7d65a9ccaa8145f1d8b2f01";
  }

  static const char* value(const audiogesture::BextractorResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<audiogesture::BextractorResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "audiogesture/Bextractor";
  }

  static const char* value(const audiogesture::BextractorResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // AUDIOGESTURE_SERVICE_BEXTRACTOR_H

