/* Auto-generated by genmsg_cpp for file /home/haikalpribadi/Workspace/ROS/radiophonic/audiogesture/srv/GetSampleFile.srv */
#ifndef AUDIOGESTURE_SERVICE_GETSAMPLEFILE_H
#define AUDIOGESTURE_SERVICE_GETSAMPLEFILE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace audiogesture
{
template <class ContainerAllocator>
struct GetSampleFileRequest_ {
  typedef GetSampleFileRequest_<ContainerAllocator> Type;

  GetSampleFileRequest_()
  : name()
  {
  }

  GetSampleFileRequest_(const ContainerAllocator& _alloc)
  : name(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  name;


  typedef boost::shared_ptr< ::audiogesture::GetSampleFileRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::audiogesture::GetSampleFileRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GetSampleFileRequest
typedef  ::audiogesture::GetSampleFileRequest_<std::allocator<void> > GetSampleFileRequest;

typedef boost::shared_ptr< ::audiogesture::GetSampleFileRequest> GetSampleFileRequestPtr;
typedef boost::shared_ptr< ::audiogesture::GetSampleFileRequest const> GetSampleFileRequestConstPtr;



template <class ContainerAllocator>
struct GetSampleFileResponse_ {
  typedef GetSampleFileResponse_<ContainerAllocator> Type;

  GetSampleFileResponse_()
  : file()
  {
  }

  GetSampleFileResponse_(const ContainerAllocator& _alloc)
  : file(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _file_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  file;


  typedef boost::shared_ptr< ::audiogesture::GetSampleFileResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::audiogesture::GetSampleFileResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GetSampleFileResponse
typedef  ::audiogesture::GetSampleFileResponse_<std::allocator<void> > GetSampleFileResponse;

typedef boost::shared_ptr< ::audiogesture::GetSampleFileResponse> GetSampleFileResponsePtr;
typedef boost::shared_ptr< ::audiogesture::GetSampleFileResponse const> GetSampleFileResponseConstPtr;


struct GetSampleFile
{

typedef GetSampleFileRequest Request;
typedef GetSampleFileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct GetSampleFile
} // namespace audiogesture

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::audiogesture::GetSampleFileRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::audiogesture::GetSampleFileRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::audiogesture::GetSampleFileRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const  ::audiogesture::GetSampleFileRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc1f3d28f1b044c87ULL;
  static const uint64_t static_value2 = 0x1e6eff2e9fc3c667ULL;
};

template<class ContainerAllocator>
struct DataType< ::audiogesture::GetSampleFileRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "audiogesture/GetSampleFileRequest";
  }

  static const char* value(const  ::audiogesture::GetSampleFileRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::audiogesture::GetSampleFileRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string name\n\
\n\
";
  }

  static const char* value(const  ::audiogesture::GetSampleFileRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::audiogesture::GetSampleFileResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::audiogesture::GetSampleFileResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::audiogesture::GetSampleFileResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e5aa404286053ca7f6cc32f23f37b85d";
  }

  static const char* value(const  ::audiogesture::GetSampleFileResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe5aa404286053ca7ULL;
  static const uint64_t static_value2 = 0xf6cc32f23f37b85dULL;
};

template<class ContainerAllocator>
struct DataType< ::audiogesture::GetSampleFileResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "audiogesture/GetSampleFileResponse";
  }

  static const char* value(const  ::audiogesture::GetSampleFileResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::audiogesture::GetSampleFileResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string file\n\
\n\
\n\
";
  }

  static const char* value(const  ::audiogesture::GetSampleFileResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::audiogesture::GetSampleFileRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.name);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetSampleFileRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::audiogesture::GetSampleFileResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.file);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetSampleFileResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<audiogesture::GetSampleFile> {
  static const char* value() 
  {
    return "65741e102dfdf1ce689c0b8ed7c755c0";
  }

  static const char* value(const audiogesture::GetSampleFile&) { return value(); } 
};

template<>
struct DataType<audiogesture::GetSampleFile> {
  static const char* value() 
  {
    return "audiogesture/GetSampleFile";
  }

  static const char* value(const audiogesture::GetSampleFile&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<audiogesture::GetSampleFileRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "65741e102dfdf1ce689c0b8ed7c755c0";
  }

  static const char* value(const audiogesture::GetSampleFileRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<audiogesture::GetSampleFileRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "audiogesture/GetSampleFile";
  }

  static const char* value(const audiogesture::GetSampleFileRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<audiogesture::GetSampleFileResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "65741e102dfdf1ce689c0b8ed7c755c0";
  }

  static const char* value(const audiogesture::GetSampleFileResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<audiogesture::GetSampleFileResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "audiogesture/GetSampleFile";
  }

  static const char* value(const audiogesture::GetSampleFileResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // AUDIOGESTURE_SERVICE_GETSAMPLEFILE_H

