(cl:defpackage audiogesture-msg
  (:use )
  (:export
   "<TRAINERSTATUS>"
   "TRAINERSTATUS"
   "<EXTRACTORSTATUS>"
   "EXTRACTORSTATUS"
   "<FEATUREVECTOR>"
   "FEATUREVECTOR"
   "<STRINGS>"
   "STRINGS"
   "<PLAYERCOMMAND>"
   "PLAYERCOMMAND"
   "<PROCESSEDOUTPUT>"
   "PROCESSEDOUTPUT"
   "<TRAINERLOGSTATUS>"
   "TRAINERLOGSTATUS"
  ))

