(cl:defpackage audiogesture-srv
  (:use )
  (:export
   "GETSAMPLES"
   "<GETSAMPLES-REQUEST>"
   "GETSAMPLES-REQUEST"
   "<GETSAMPLES-RESPONSE>"
   "GETSAMPLES-RESPONSE"
   "GETSAMPLEFILE"
   "<GETSAMPLEFILE-REQUEST>"
   "GETSAMPLEFILE-REQUEST"
   "<GETSAMPLEFILE-RESPONSE>"
   "GETSAMPLEFILE-RESPONSE"
  ))

