(cl:defpackage audiogesture-srv
  (:use )
  (:export
   "GETFILE"
   "<GETFILE-REQUEST>"
   "GETFILE-REQUEST"
   "<GETFILE-RESPONSE>"
   "GETFILE-RESPONSE"
   "GETSAMPLES"
   "<GETSAMPLES-REQUEST>"
   "GETSAMPLES-REQUEST"
   "<GETSAMPLES-RESPONSE>"
   "GETSAMPLES-RESPONSE"
  ))

